In [10]:
import numpy as np
a = np.array([1,2,3,4,5],dtype = 'i')
b = np.array((1,2,3,4,5), dtype = 'f')

In [4]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float32')

In [14]:
 a = np.array([[1,2,3],[4,5,6]])

In [16]:
a.ndim

2

In [18]:
a[0,2]

3

In [26]:
B = np.array([[1,2,3,-1],[2,4,5,9]])

In [28]:
B.ndim

2

In [30]:
B[1,2]

5

In [32]:
C = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [34]:
C.ndim

3

In [36]:
C[1,0,2]

-3

In [38]:
type(C)

numpy.ndarray

In [40]:
C.shape

(2, 3, 3)

In [42]:
C.shape[0]

2

In [44]:
C.size  

18

In [48]:
A = np.arange(100)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [52]:
B = np.arange(20,100)
print(B)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [56]:
D = np.arange(20,100,3)
print(D)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [58]:
M = np.random.permutation(np.arange(10))
print(M)

[8 3 6 9 4 7 1 5 0 2]


In [60]:
 np.random.randint??

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [64]:
np.random.randint(20,100)

65

In [74]:
A = np.random.rand(100)
print(A)

[0.8236718  0.95158515 0.09776186 0.77908112 0.87167294 0.00183631
 0.12346413 0.4073399  0.81843963 0.73189548 0.62596939 0.09302171
 0.75665476 0.80949125 0.51600858 0.25264458 0.23424584 0.16940034
 0.32614906 0.54674471 0.84435562 0.77461838 0.19668894 0.15924962
 0.48478233 0.70298584 0.20434811 0.93983706 0.71097547 0.7800763
 0.59159257 0.7369784  0.6777431  0.64563278 0.83710274 0.97650878
 0.36124152 0.83172803 0.01566695 0.85528917 0.46296319 0.78923595
 0.16276339 0.04883195 0.38301785 0.07545301 0.02027309 0.03383075
 0.41943855 0.03476968 0.39234127 0.13239925 0.96269139 0.58331473
 0.72278925 0.64820707 0.89604464 0.69214833 0.93426291 0.43903895
 0.30727197 0.13922692 0.30227906 0.63607448 0.70228577 0.10829457
 0.99629335 0.63842059 0.95264931 0.11377279 0.10827423 0.37029087
 0.74551215 0.34872757 0.74717985 0.73314933 0.33873349 0.98796271
 0.65350177 0.87493717 0.10939244 0.18020689 0.1684442  0.32072742
 0.78888509 0.13506693 0.56349139 0.77718114 0.25294414 0.89753

In [78]:
D = np.random.rand(2,3)
print(D)

[[0.94811216 0.99744076 0.04452153]
 [0.30299943 0.31577911 0.68402155]]


In [80]:
D.ndim

2

In [82]:
C = np.random.rand(2,3,4,2)
print(C)

[[[[0.51914434 0.71271208]
   [0.08563055 0.57656289]
   [0.4875586  0.8248975 ]
   [0.93955441 0.81807728]]

  [[0.91612449 0.92894199]
   [0.51626535 0.583888  ]
   [0.90765404 0.56892325]
   [0.22222475 0.01634779]]

  [[0.87700137 0.44224972]
   [0.32192974 0.85785487]
   [0.48778976 0.81998125]
   [0.97946336 0.70981908]]]


 [[[0.54675154 0.01605586]
   [0.57410537 0.74772399]
   [0.72752496 0.98016026]
   [0.81468915 0.64737886]]

  [[0.82667747 0.01719326]
   [0.80656933 0.8007923 ]
   [0.57640893 0.02903474]
   [0.16653645 0.87861731]]

  [[0.35637025 0.20974974]
   [0.19871698 0.7933278 ]
   [0.75417651 0.12862677]
   [0.78600183 0.68244686]]]]


In [84]:
C.ndim

4

In [86]:
type(C)

numpy.ndarray

In [88]:
D = np.arange(100)
print(D)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [90]:
D.shape

(100,)

In [92]:
D = np.arange(100).reshape(4,25)
print(D)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [94]:
D.shape

(4, 25)

In [96]:
D = np.arange(100).reshape(4,5,5)
print(D)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [98]:
print(np.zeros)

<built-in function zeros>


In [100]:
A = np.arange(100)

In [102]:
b = A[3:10]
print(b)

[3 4 5 6 7 8 9]


In [104]:
b [0] = -1200

In [106]:
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [108]:
A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [110]:
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [112]:
A[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [114]:
A[::-1]

array([   99,    98,    97,    96,    95,    94,    93,    92,    91,
          90,    89,    88,    87,    86,    85,    84,    83,    82,
          81,    80,    79,    78,    77,    76,    75,    74,    73,
          72,    71,    70,    69,    68,    67,    66,    65,    64,
          63,    62,    61,    60,    59,    58,    57,    56,    55,
          54,    53,    52,    51,    50,    49,    48,    47,    46,
          45,    44,    43,    42,    41,    40,    39,    38,    37,
          36,    35,    34,    33,    32,    31,    30,    29,    28,
          27,    26,    25,    24,    23,    22,    21,    20,    19,
          18,    17,    16,    15,    14,    13,    12,    11,    10,
           9,     8,     7,     6,     5,     4, -1200,     2,     1,
           0])

In [124]:
idx = np.argwhere(A==-1200)
print(idx)

[[3]]


In [126]:
type(idx)

numpy.ndarray

In [128]:
idx = np.argwhere(A==-1200)[0][0]
print(idx)

3


In [130]:
type(idx)

numpy.int64

In [132]:
A[idx] = 3

In [134]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [142]:
B = np.round(10*np.random.rand(5,4))

In [144]:
B

array([[ 0.,  5.,  9.,  2.],
       [ 7.,  7.,  0.,  6.],
       [ 5.,  7.,  2.,  1.],
       [ 1.,  9., 10.,  7.],
       [ 6.,  7.,  8.,  9.]])

In [148]:
B[1,2]

0.0

In [150]:
B[1,:]

array([7., 7., 0., 6.])

In [154]:
B[:,1]

array([5., 7., 7., 9., 7.])

In [158]:
B[1:3,2:4]

array([[0., 6.],
       [2., 1.]])

In [160]:
B.T

array([[ 0.,  7.,  5.,  1.,  6.],
       [ 5.,  7.,  7.,  9.,  7.],
       [ 9.,  0.,  2., 10.,  8.],
       [ 2.,  6.,  1.,  7.,  9.]])

In [162]:
import numpy.linalg as la

In [164]:
la.inv(np.random.rand(3,3))

array([[  2.85229866,   4.02314685,  -3.47076261],
       [-14.78818434, -14.15228068,  16.87471743],
       [ 14.47065103,  11.4052032 , -13.66459098]])

In [166]:
B.sort(axis=0)

In [168]:
B

array([[ 0.,  5.,  0.,  1.],
       [ 1.,  7.,  2.,  2.],
       [ 5.,  7.,  8.,  6.],
       [ 6.,  7.,  9.,  7.],
       [ 7.,  9., 10.,  9.]])

In [170]:
B.sort(axis=1)

In [172]:
B

array([[ 0.,  0.,  1.,  5.],
       [ 1.,  2.,  2.,  7.],
       [ 5.,  6.,  7.,  8.],
       [ 6.,  7.,  7.,  9.],
       [ 7.,  9.,  9., 10.]])

In [174]:
A = np.arange(100)

In [184]:
B = A[[3,5,6]] 

In [186]:
B

array([3, 5, 6])

In [188]:
B[0]=-4

In [190]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [192]:
B = A[A<40]

In [194]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [196]:
B = A[(A<40) & (A>30)]

In [198]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [200]:
A = np.round(10*np.random.rand(2,3))

In [202]:
A

array([[6., 1., 9.],
       [7., 9., 2.]])

In [204]:
A+3

array([[ 9.,  4., 12.],
       [10., 12.,  5.]])

In [206]:
A + (np.arange(2).reshape(2,1))

array([[ 6.,  1.,  9.],
       [ 8., 10.,  3.]])

In [212]:
(np.arange(2).reshape(2,1))

array([[0],
       [1]])

In [216]:
B = np.round(10*np.random.rand(2,2))

In [218]:
B

array([[8., 7.],
       [9., 7.]])

In [220]:
A

array([[6., 1., 9.],
       [7., 9., 2.]])

In [222]:
B

array([[8., 7.],
       [9., 7.]])

In [224]:
C = np.hstack((A,B))

In [226]:
C

array([[6., 1., 9., 8., 7.],
       [7., 9., 2., 9., 7.]])

In [228]:
A = np.random.permutation(np.arange(10))

In [230]:
A

array([0, 5, 4, 6, 1, 3, 2, 9, 7, 8])

In [232]:
A.sort()

In [234]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [240]:
A = np.array(["abc","eifweui","123rjf","89ugceu"])

In [242]:
A.sort()

In [244]:
A

array(['123rjf', '89ugceu', 'abc', 'eifweui'], dtype='<U7')

# Feel the speed of Numpy

In [249]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B)

116 ms ± 4.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.21 ms ± 145 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [255]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [257]:
%timeit mySum(B)

162 ms ± 8.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
